# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: flake8
  - id: no-commit-to-branch
    args: [--branch, main, --branch, develop]


       


